### ISSUE TITLE
tmp dir issue in `SORT_GTF`

### ISSUE THREAD

**Issue by lianov** [nf-core/scnanoseq#2]
### Description of the bug

Temporary file creation issue noted when using singularity container for `SORT_GTF` ; seems to be a container specific issue and thus we may need to find an alternative container. Note this was only encountered with the full file test.

### Command used and terminal output

params:

```yaml
# names/email
multiqc_title: "scnanoseq_complete_GridION_test"

# input samplesheet
input: "./samplesheet.csv"

# Genome references
fasta: "/data/project/U_BDS/References/GENCODE/mm10/release_M20/Genome/GRCm38.primary_assembly.genome.fa"
gtf: "/data/project/U_BDS/References/GENCODE/mm10/release_M20/GTF/gencode.vM20.annotation.gtf"

# other params
skip_trimming: false
trimming_software: "nanofilt"
skip_nanoplot: false 
#skip_nanoplot: true

# fastq options
split_amount: 0 

# barcode options
cell_barcode_pattern: ""
cell_amount: 1000
identifier_pattern: "fixed_seq_1,cell_barcode_1,umi_1,fixed_seq_2"
cell_barcode_lengths: "16"
umi_lengths: "12"
fixed_seqs: "CTACACGACGCTCTTCCGATCT, TTTTTTTTTT"
#intron_retention_method: "1"
#counts_level: "gene" # null by default

```

execution of pipeline:

```console
nextflow run main.nf \
    -params-file ./params.yml \
    --outdir ./results \
    -profile cheaha \
    -resume
```

```
Command error:
  sort: cannot create temporary file in '/scratch/lianov': No such file or directory
```
```


### Relevant files

_No response_

### System information

UAB HPC - Cheaha (with cheaha config)
